routes/admin.php
<?php

/**
 *@author arcytan
 *@date 2017-03-06
 *@description 后台路由
 */
Route::group(['namespace'=>'Admin','prefix'=>'admin' , 'as'=>'admin.'] ,function(){
	
	/* 登录页 */
	Route::match(['get','post'], '/' ,['uses'=>'LoginController@login']);
	Route::match(['get','post'], 'login' ,['uses'=>'LoginController@login','as'=>'login']);
	Route::get('logout' , ['uses'=>'LoginController@logout', 'as'=>'logout']);
	Route::get('mkpsd' , ['uses'=>'LoginController@mkpsd']);

	/* 后台首页 */
	// Route::get('/', 'HomeController@home');
	Route::get('home', ['uses'=>'HomeController@home', 'as'=>'home']);
	Route::get('index', ['uses'=>'HomeController@index', 'as'=>'home.index']);

	/* 权限路由 */
	Route::group(['namespace'=>'Auth', 'prefix'=>'auth', 'as'=>'auth.'], function(){
		Route::get('rule/list', ['uses'=>'RuleController@lists', 'as'=>'rule.list']);
		Route::match(['get','post'],'rule/add', ['uses'=>'RuleController@add', 'as'=>'rule.add']);
		Route::match(['get','post'],'rule/edit',['uses'=>'RuleController@edit', 'as'=>'rule.edit']);
		Route::post('rule/changeStatus',['uses'=>'RuleController@changeStatus', 'as'=>'rule.changeStatus']);
		Route::post('rule/del',['uses'=>'RuleController@del', 'as'=>'rule.del']);

		//角色路由
		Route::get('role/list',['uses'=>'RoleController@lists', 'as'=>'role.list']);
		Route::match(['get','post'],'role/add', ['uses'=>'RoleController@add', 'as'=>'role.add']);
		Route::match(['get','post'],'role/edit',['uses'=>'RoleController@edit', 'as'=>'role.edit']);
		Route::post('role/changeStatus',['uses'=>'RoleController@changeStatus', 'as'=>'role.changeStatus']);
		Route::post('role/del',['uses'=>'RoleController@del', 'as'=>'role.del']);
	});


	/* 管理员管理路由 */
	// Route::get('manager','ManagerController@lists');
	Route::get('manager/list',['uses'=>'ManagerController@lists','as'=>'manager.list']);
	Route::match(['get','post'],'manager/add',['uses'=>'ManagerController@add','as'=>'manager.add']);
	Route::match(['get','post'],'manager/edit',['uses'=>'ManagerController@edit','as'=>'manager.edit']);
	Route::post('manager/changeStatus',['uses'=>'ManagerController@changeStatus', 'as'=>'manager.changeStatus']);
	Route::post('manager/del',['uses'=>'ManagerController@del', 'as'=>'manager.del']);
	//修改管理员个人信息
	Route::match(['get','post'],'manager/editProfile',['uses'=>'ManagerController@editProfile','as'=>'manager.editProfile']); 
	//修改管理员密码
	Route::match(['get','post'],'manager/editPassword',['uses'=>'ManagerController@editPassword','as'=>'manager.editPassword']);
	//为管理员分配角色 
	Route::match(['get','post'],'manager/role',['uses'=>'ManagerController@role','as'=>'manager.role']); 
	
	//附件路由
	Route::group(['namespace'=>'Attachment', 'prefix'=>'attachment', 'as'=>'attachment.'], function(){
		Route::post('upload/save',['uses'=>'UploadController@save','as'=>'upload.save']);
	});
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function (Request $request) {
    return 'hhh';
});

Route::get('index/test' , ['as'=>'index_test', function (Request $request){
		$route = Route::current();
		$name = Route::currentRouteName();
		$action = Route::currentRouteAction();

		var_dump($route->as);
		var_dump($name);
		var_dump($action);
		return null;
	}]
);

Route::get('index/test/{test}' , ['as'=>'index_test_test',function (Request $request){
		$route = Route::current();
		$name = Route::currentRouteName();
		$action = Route::currentRouteAction();

		var_dump('tset');
		var_dump($route->uri);
		var_dump($name);
		var_dump($action);
		return null;
	}]
);

Auth::routes();

Route::get('/home', 'HomeController@index');*/

/* 导入管理后台路由文件 */
require('admin.php');

resources/views/admin/home.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title>A+ 管理后台</title>

    <!--[if lt IE 9]>
    <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->

    <link rel="shortcut icon" href="favicon.ico">
    <link href="/admin/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/admin/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="/admin/css/animate.min.css" rel="stylesheet">
    <link href="/admin/js/plugins/layui/css/layui.css" rel="stylesheet">
    <link href="/admin/css/style.min862f.css?v=4.1.0" rel="stylesheet">
    <link href="/admin/css/aplus.style.css?v=4.1.0" rel="stylesheet">
</head>

<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="logo-normal">
                            <img src="/admin/img/logo2.png" alt="">
                        </div>
                        <div class="logo-element">A+</div>
                    </li>
                    
                    <!-- 生成菜单 -->
                    {!! $menu_str !!}
                    <!-- //生成菜单 -->
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <!-- 全局搜索框 -->
                        <!-- <form role="search" class="navbar-form-custom" method="post" action="#">
                            <div class="form-group">
                                <input type="text" placeholder="请输入关键字" class="form-control" name="top-search" id="top-search">
                            </div>
                        </form> -->
                        <!-- 全局搜索框结束 -->
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li class="dropdown hidden-xs  profile-element">
                            <span class="clear"></span>
                            <span class="pull-left">
                                <img alt="image" class="img-circle" src="{{ $SELF->headimgurl }}" />
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle pull-right" href="#">
                                <span class="block m-t-xs" style="margin-top:16px;"><strong class="font-bold">{{ $SELF->name }}<b class="caret"></b></strong></span>
                                <!-- <span class="text-muted text-xs block">超级管理员<b class="caret"></b></span> -->
                            </a>
                            <span class="clear"></span>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="J_menuItem" href="{{ URL::route('admin.manager.editPassword') }}">修改密码</a>
                                </li>
                                <li><a class="J_menuItem" href="{{ URL::route('admin.manager.editProfile') }}">修改资料</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="{{ URL::route('admin.logout') }}">安全退出</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="row content-tabs">
                <button class="roll-nav roll-left J_tabLeft"><i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab" data-id="{{ URL::route('admin.home.index') }}">首页</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight"><i class="fa fa-forward"></i>
                </button>
                <div class="btn-group btn-group-op roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive"><a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <li class="J_tabCloseAll"><a>关闭全部选项卡</a>
                        </li>
                        <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                        </li>
                    </ul>
                </div>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">清除缓存<span class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li><a>站点数据</a>
                        </li>
                        <li class="divider"></li>
                        <li><a>站点模板</a>
                        </li>
                        <li class="divider"></li>
                        <li><a>网站日志</a>
                        </li>
                    </ul>
                </div>
                <a href="{{ URL::route('admin.logout') }}" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> 退出</a>
            </div>
            <div class="row J_mainContent" id="content-main">
                <!-- 正式内容iframe -->
                <iframe class="J_iframe" name="iframe-1" width="100%" height="100%" data-id="{{ URL::route('admin.home.index') }}" src="{{ URL::route('admin.home.index') }}" frameborder="0" seamless></iframe>
                <!-- //正式内容iframe结束 -->
            </div>
            <div class="footer">
                <div class="pull-right">&copy; 2014-2015 <a href="http://www.arcy.cn/" target="_blank">A+ 管理后台</a>
                </div>
            </div>
        </div>
        <!--右侧部分结束-->
    </div>
    <script src="/admin/js/jquery.min.js?v=2.1.4" type="text/javascript"></script>
    <script src="/admin/js/bootstrap.min.js?v=3.3.6" type="text/javascript"></script>
    <script src="/admin/js/plugins/metisMenu/jquery.metisMenu.js" type="text/javascript"></script>
    <script src="/admin/js/plugins/slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/admin/js/plugins/layui/layui.js" type="text/javascript"></script>
    <script src="/admin/js/hplus.min.js?v=4.1.0" type="text/javascript"></script>
    <script src="/admin/js/contabs.min.js" type="text/javascript"></script>
    <script src="/admin/js/plugins/pace/pace.min.js" type="text/javascript"></script>
</body>
</html>

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html>
<head>

    <title>后台首页</title>
    @include('admin.layouts.style')
</head>

<body class="gray-bg">
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
			<div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>系统信息</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <tbody>
                        @foreach ($info as $key=>$val)
                        	<tr>
                        		<td>{{ $key }}</td>
                        		<td>{{ $val }}</td>
                        	</tr>
						@endforeach
							<tr>
								<td>服务器空间使用率</td>
								<td>
									<div class="col-sm-4" style="padding: 0;">
										<h5>{{ $disk_precent }}%</h5>
										<div class="progress progress-mini">
				                            <div style="width: {{ $disk_precent }}%;" class="progress-bar"></div>
				                        </div>	
									</div>
                        		</td>
							</tr>
                        </tbody>
                    </table>

                </div>
			</div>

			<div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>开发团队</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <tbody>
                        	<tr>
                        		<td>部门名称</td>
                        		<td>{{ config('system.team_name') }}</td>
                        	</tr> 
                        	<tr>
                        		<td>开发人员</td>
                        		<td>
                        			@foreach (config('system.product_author') as $val)
                        			<a href="{{ $val['url'] }}" target="_blank">{{ $val['name'] }}</a>({{$val['email']}}) 
                        			@endforeach
                        		</td>
                        	</tr>
                        </tbody>
                    </table>
                </div>
            </div>
		</div>
	</div>
</div>
@include('admin.layouts.script')
</body>
</html>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
<title>世宇科技售后服务中心——后台登录</title>

<!--common css-->
<link href="/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/admin/css/aplus.style.css" rel="stylesheet">
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<![endif]-->
</head>
<body class="signin-body">
<div class="container signin-container">
    <div class="text-center signin-head">
        <img src="/admin/img/logo.png" style="width: 104px;">
    </div>
    <form class="signin-form" action="{{ URL::route('admin.login') }}" method="post" data-event="onform">
        {{ csrf_field() }}
        <div class="form-group signin-form-group">
            <input datatype="s3-15" nullmsg="用户名不能为空！" errormsg="用户名介乎4到16个字符！" type="text" class="signin-form-control" name="username" id="username" placeholder="账号" autocomplete="off" />
        </div>
        <div class="form-group signin-form-group">
            <input datatype="s6-30" nullmsg="密码不能为空！" errormsg="密码介乎8到30个字符！" type="password" class="signin-form-control" name="password" id="password" placeholder="密码" autocomplete="off" />
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-lg btn-login btn-block">登 陆</button>
        </div>
    </form>
    <p class="text-center text-grap"><a href="http://www.sy.cn" style="color:#7A7676;" target="_blank">中山世宇动漫科技有限公司</a> &copy; 版权所有</p>
</div>
<!--import third-party js-->
<script type="text/javascript">
CT = {
    JS  : '/admin/js/',
    CSS : '/admin/css/',
    IMG : '/admin/img/',
    THIRD : '/admin/third-party/',
    URL : document.URL
}
</script>
<style type="text/css">
    .Validform_error{
        border-bottom-color: #FF0000;
    }
</style>
<script type="text/javascript" src="/admin/js/jquery.min.js"></script>
<script type="text/javascript" src="/admin/js/bootstrap.min.js"></script>
<script src="/admin/js/atr-event.js"></script>
<script src="/admin/js/functions.js"></script>
</body>
</html>