routes/admin.php
<?php

/**
 *@author arcytan
 *@date 2017-03-06
 *@description 后台路由
 */
Route::group(['namespace'=>'Admin','prefix'=>'admin' , 'as'=>'admin.'] ,function(){
	
	/* 登录页 */
	Route::match(['get','post'], '/' ,['uses'=>'LoginController@login']);
	Route::match(['get','post'], 'login' ,['uses'=>'LoginController@login','as'=>'login']);
	Route::get('logout' , ['uses'=>'LoginController@logout', 'as'=>'logout']);
	Route::get('mkpsd' , ['uses'=>'LoginController@mkpsd']);

	/* 后台首页 */
	// Route::get('/', 'HomeController@home');
	Route::get('home', ['uses'=>'HomeController@home', 'as'=>'home']);
	Route::get('index', ['uses'=>'HomeController@index', 'as'=>'home.index']);

	/* 权限路由 */
	Route::group(['namespace'=>'Auth', 'prefix'=>'auth', 'as'=>'auth.'], function(){
		Route::get('rule/list', ['uses'=>'RuleController@lists', 'as'=>'rule.list']);
		Route::match(['get','post'],'rule/add', ['uses'=>'RuleController@add', 'as'=>'rule.add']);
		Route::match(['get','post'],'rule/edit',['uses'=>'RuleController@edit', 'as'=>'rule.edit']);
		Route::post('rule/changeStatus',['uses'=>'RuleController@changeStatus', 'as'=>'rule.changeStatus']);
		Route::post('rule/del',['uses'=>'RuleController@del', 'as'=>'rule.del']);

		//角色路由
		Route::get('role/list',['uses'=>'RoleController@lists', 'as'=>'role.list']);
		Route::match(['get','post'],'role/add', ['uses'=>'RoleController@add', 'as'=>'role.add']);
		Route::match(['get','post'],'role/edit',['uses'=>'RoleController@edit', 'as'=>'role.edit']);
		Route::post('role/changeStatus',['uses'=>'RoleController@changeStatus', 'as'=>'role.changeStatus']);
		Route::post('role/del',['uses'=>'RoleController@del', 'as'=>'role.del']);
	});


	/* 管理员管理路由 */
	// Route::get('manager','ManagerController@lists');
	Route::get('manager/list',['uses'=>'ManagerController@lists','as'=>'manager.list']);
	Route::match(['get','post'],'manager/add',['uses'=>'ManagerController@add','as'=>'manager.add']);
	Route::match(['get','post'],'manager/edit',['uses'=>'ManagerController@edit','as'=>'manager.edit']);
	Route::post('manager/changeStatus',['uses'=>'ManagerController@changeStatus', 'as'=>'manager.changeStatus']);
	Route::post('manager/del',['uses'=>'ManagerController@del', 'as'=>'manager.del']);
	//修改管理员个人信息
	Route::match(['get','post'],'manager/editProfile',['uses'=>'ManagerController@editProfile','as'=>'manager.editProfile']); 
	//修改管理员密码
	Route::match(['get','post'],'manager/editPassword',['uses'=>'ManagerController@editPassword','as'=>'manager.editPassword']);
	//为管理员分配角色 
	Route::match(['get','post'],'manager/role',['uses'=>'ManagerController@role','as'=>'manager.role']); 
	
	//附件路由
	Route::group(['namespace'=>'Attachment', 'prefix'=>'attachment', 'as'=>'attachment.'], function(){
		Route::post('upload/save',['uses'=>'UploadController@save','as'=>'upload.save']);
	});
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function (Request $request) {
    return 'hhh';
});

Route::get('index/test' , ['as'=>'index_test', function (Request $request){
		$route = Route::current();
		$name = Route::currentRouteName();
		$action = Route::currentRouteAction();

		var_dump($route->as);
		var_dump($name);
		var_dump($action);
		return null;
	}]
);

Route::get('index/test/{test}' , ['as'=>'index_test_test',function (Request $request){
		$route = Route::current();
		$name = Route::currentRouteName();
		$action = Route::currentRouteAction();

		var_dump('tset');
		var_dump($route->uri);
		var_dump($name);
		var_dump($action);
		return null;
	}]
);

Auth::routes();

Route::get('/home', 'HomeController@index');*/

/* 导入管理后台路由文件 */
require('admin.php');

app/Http/Controllers/Admin/ManagerController.php
<?php
namespace App\Http\Controllers\Admin;

use URL;
use Illuminate\Http\Request;
use App\Model\AdminUser;
use App\Model\AdminRole;
use App\Model\AdminUserRole;
use Admin;
use Hash;

class ManagerController extends Controller{

	public function lists(Request $request){
		/* 实例化模型 */
		$adminUser  = new \App\Model\AdminUser();
		
		$list = $adminUser->page(15);

		$data = ['lists'=>$list];
		return view('admin.manager.manager_list',$data);
	}

	public function add(Request $request){

		if($request->isMethod('get')){
			$data = [];
			return view('admin.manager.manager_add' , $data);
		}

		//处理post数据
		$username = $request->input('username');
		$name = $request->input('name');
		$password = $request->input('password');
		$headimgurl = $request->input('headimgurl');
		$status = ($request->input('status') == 'on') ? 1 : 0;

		if(!between($username, 4,16)){
			return $this->error('用户名介乎4-16个字符！');
		}elseif (!between($name, 2,16)) {
			return $this->error('姓名介乎2-16个字符！');
		}elseif (is_empty($password)) {
			return $this->error('密码不能为空！');
		}elseif (!between($password, 8,30)) {
			return $this->error('密码介乎8-30个字符');
		}elseif (is_empty($headimgurl)) {
			return $this->error('头像不能为空！');
		}elseif ($this->isExistUsername($username)) {
			return $this->error('用户名已存在！');
		}

		$insert = [
			'username'=>$username,
			'name'=>$name,
			'password'=>$password,
			'headimgurl'=>$headimgurl,
			'status'=>$status
		];

		$adminUser = new \App\Model\AdminUser();

		if($adminUser->create($insert)){
			return $this->success('添加成功！',1,URL::route('admin.manager.add'));
		}else{
			return $this->error('添加失败！');
		}
	}

	public function edit(Request $request){
		$id = $request->input('id');

		if(!is_id($id)){
			return $this->error('管理员ID非法！');
		}

		if(Admin::currentAdminId() == $id){
			return $this->error('修改当前用户请在个人资料中修改！');
		}

		// $adminUser = new \App\Model\AdminUser();
		// $info = $adminUser->select(['admin_id','username','name','status','headimgurl'])->find($id);
		$info = \App\Model\AdminUser::select(['admin_id','username','name','status','headimgurl'])->find($id);

		if(is_null($info)){
			return $this->error('管理员不存在！');
		}

		if($request->isMethod('get')){
			$data = ['info'=>$info];
			return view('admin.manager.manager_edit',$data);
		}

		// $username = $request->input('username');
		$name = $request->input('name');
		$password = $request->input('password');
		$headimgurl = $request->input('headimgurl');
		$status = ($request->input('status') == 'on') ? 1 : 0;

		// if(!between($username,4,16)){
		// 	return $this->alertJson('用户名介乎4-16个字符！');
		// }else
		if (!between($name,2,16)) {
			return $this->error('用户姓名介乎2-16个字符！');
		}

		if(!is_empty($password)) {
			if(!between($password,8,16)) return $this->error('用户密码介乎8-16个字符！');
			$adminUser->password = $password;
		}
			
		if(is_empty($headimgurl)){
			return $this->error('用户头像不能为空！');
		}

		$info->name = $name;
		$info->headimgurl = $headimgurl;
		$info->status = $status;
		$info->password = $password;

		if($info->save()){
			return $this->success('修改成功！' , URL::route('admin.manager.list'));
		}else{
			return $this->error('修改失败！');
		}

	}

	public function changeStatus(Request $request){
		$id = $request->input('id');
		$option = $request->input('option');

		if (!is_id($id)) {
			return $this->error('管理员ID非法！');
		}elseif (is_empty($option)) {
			return $this->error('option不能为空！');
		}

		if(Admin::currentAdminId()==$id){
			return $this->error('不能禁用当前登录用户！');
		}

		$adminRule = new \App\Model\AdminUser();
		$status = $adminRule->changeStatus($option,$id);

		if($status === false){
			return $this->error('更新失败！');
		}else{
			return $this->success('更新成功！' , null, ['status'=>$status]);
		}
	}

	public function del(Request $request){
		$id = $request->input('id');
		if (!is_id($id)) {
			return $this->error('管理员ID非法！');
		}

		//管理员删除管理暂时不开放
	}

	/**
	 * 个人信息修改
	 */
	public function editProfile(Request $request){

		//获取信息
		$profile = Admin::currentAdminInfo();

		if($request->isMethod('get')){
			$data = ['info'=>$profile];
			return view('admin.manager.manager_edit_profile',$data);
		}

		$name = $request->input('name');
		$headimgurl = $request->input('headimgurl');

		if (!between($name,2,16)) {
			return $this->error('用户姓名介乎2-16个字符！');
		}
			
		if(is_empty($headimgurl)){
			return $this->error('用户头像不能为空！');
		}

		$info = AdminUser::find(Admin::currentAdminId());
		$info->name = $name;
		$info->headimgurl = $headimgurl;

		if($info->save()){
			Admin::updateLogin($info);
			return $this->success('修改成功！' , URL::route('admin.manager.list'));
		}else{
			return $this->error('修改失败！');
		}
	}

	/**
	 * 修改密码
	 */
	public function editPassword(Request $request){
		if($request->isMethod('get')){
			return view('admin.manager.manager_edit_password');
		}

		$info = AdminUser::find(Admin::currentAdminId());

		$old_pass = $request->input('old_pass');
		$new_pass = $request->input('new_pass');
		$com_pass = $request->input('com_pass');

		if(!between($old_pass,8,16)){
			return $this->error('旧密码介乎8-16个字符！');
		}elseif (!Hash::check($old_pass,$info->password)) {
			return $this->error('旧密码不正确！');
		}elseif (!between($new_pass,8,16)) {
			return $this->error('新密码介乎8-16个字符！');
		}elseif ($new_pass != $com_pass) {
			return $this->error('确认密码和新密码不一致！');
		}

		$info->password = $new_pass;

		if($info->save()){
			Admin::updateLogin($info);
			return $this->success('密码更新成功！', URL::route('admin.manager.editPassword'));
		}else{
			return $this->error('密码更新失败！');
		}
	}

	/**
     * 分配角色
	 */
	public function role(Request $request){
		$id = $request->input('id');
		if(!is_id($id)){
			return $this->error('管理员ID非法！');
		}

		//判断管理员是否存在
		$info = AdminUser::select(['username','admin_id'])->find($id);
		if(!$info){
			return $this->error('管理员不存在！');
		}

		//获取管理员拥有的角色
		$role_ids = [];
		$role_user_list = AdminUserRole::where('admin_id',$id)->first();
		if($role_user_list){
			$role_ids = str_to_arr($role_user_list->role_id);
		}

		//获取所有角色列表
		$role_list = AdminRole::where('status',1)->get();

		//如果不是提交数据，则直接显示模板
		if($request->isMethod('get')){
			$data = ['info'=>$info,'role_ids'=>$role_ids,'role_list'=>$role_list];
			return view('admin.manager.manager_role',$data);
		}

		//提交数据处理
		$role_ids = $request->input('role_id');

		if(is_array($role_ids)){
			$role_ids = implode(',', $role_ids);
		}

		//如果不分配角色则删除
		if(is_empty($role_ids)){
			if(AdminUserRole::where('admin_id',$id)->delete()){
				return $this->success('成功取消分配！',route('admin.manager.list'));
			}else{
				return $this->error('取消分配失败！');
			}
		}

		$update = ['role_id'=>$role_ids,'admin_id'=>$id];
		if(AdminUserRole::updateOrCreate(['admin_id'=>$id],$update)){
			return $this->success('分配成功！',route('admin.manager.list'));
		}else{
			return $this->error('分配失败！');
		}
		
	}

	protected function isExistUsername($username){
		$user = new \App\Model\AdminUser();

		$count = $user->where('username',$username)->count();

		if($count > 0){
			return true;
		}else{
			return false;
		}
	}
}

resources/views/admin/manager/manager_add.blade.php
@extends('admin.layouts.app')
@section('css')
<link href="/admin/css/plugins/switchery/switchery.css" rel="stylesheet">
<link href="/admin/css/plugins/webuploader/webuploader.css" rel="stylesheet">
@endsection
@section('main')
<form method="get" class="form-horizontal" data-event="onform" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">
            <input type="text" name="username" datatype="s4-16" nullmsg="用户名不能为空！" errormsg="用户名介乎4-16个字符串" class="form-control" data-trigger="hover">
            <span class="help-block m-b-none">作为登陆账号</span>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">用户姓名</label>
        <div class="col-sm-10">
            <input type="text" name="name" datatype="s2-16" nullmsg="用户姓名不能为空！" errormsg="用户姓名介乎2-16个字符！" class="form-control" data-trigger="hover">
            <span class="help-block m-b-none">介乎2-16个字符</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">登陆密码</label>
        <div class="col-sm-10">
            <input type="text" name="password" datatype="s8-16" nullmsg="登陆密码不能为空！" errormsg="登陆密码介乎8-16个字符！" class="form-control" data-trigger="hover">
            <span class="help-block m-b-none">登陆密码介乎8-16个字符</span>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">头像</label>

        <div class="col-sm-6">
   			<input type="text" datatype="*" nullmsg="头像不能为空！" name="headimgurl" class="form-control" />
        </div>

        <div class="col-sm-4">
            <a type="button" id="headimgPicker">
                <i class="fa fa-upload"></i> 上传头像
            </a>
            <span class="help-block m-b-none" id="headimgPickerTips">
                
            </span>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">是否启用</label>

        <div class="col-sm-10">
            <input type="checkbox" name="status" class="js-switch-2" checked/>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-2">
            <button class="btn btn-primary" type="submit">保存</button>
        </div>
    </div>
</form>

@endsection
@section('script')
<script type="text/javascript">
	//swich按钮
	$(function($){

		var elem2 = document.querySelector('.js-switch-2');
		var init2 = new Switchery(elem2);

        var uploader = WebUploader.create({
            //是否自动上传
            auto : true,
            // swf文件路径
            swf: CT.JS + '/plugins/webuploader/uploader.swf',

            // 文件接收服务端。
            server: '{{ URL::route("admin.attachment.upload.save") }}',

            // 选择文件的按钮。可选。
            // 内部根据当前运行是创建，可能是input元素，也可能是flash.
            pick: {
                id: '#headimgPicker',
                multiple: false
            },

            // 不压缩image, 默认如果是jpeg，文件上传前会压缩一把再上传！
            // resize: false
            accept: {
                title: 'Images',
                extensions: 'gif,jpg,jpeg,bmp,png',
                mimeTypes: 'image/*'
            },
            fileVal: 'file',
            fileSingleSizeLimit: 200*1024,
            //可重复上传
            duplicate :true
        });

        uploader.on('uploadBeforeSend',function (object ,data ,headers){
            headers['X-CSRF-TOKEN']=  $('meta[name="csrf-token"]').attr('content');
        });

        // 文件上传过程中创建进度条实时显示。
        uploader.on( 'uploadProgress', function( file, percentage ) {
            var $li = $( '#headimgPickerTips' ),
                $percent = $li.find('#headimgprocess');

            // 避免重复创建
            if ( !$percent.length ) {
                $percent = $('<div id="headimgprocess"><h5>0%</h5><div class="progress progress-mini"><div style="width: 0%;" class="progress-bar"></div></div>');
                $li.html($percent);
            }

            $percent.find('h5').html(percentage * 100 + '%').end().find('.progress-bar').css( 'width', percentage * 100 + '%' );
        });


        // 文件上传失败，显示上传出错。
        uploader.on( 'uploadError', function( file ) {
            $( '#headimgPickerTips' ).html('上传失败，请重新上传！');
        });

        //选择时出现错误
        uploader.on('error',function(type){
            if(type == 'F_EXCEED_SIZE'){
                tips('文件不能超过200K！');
            }else if (type == 'Q_TYPE_DENIED') {
                tips('文件类型不正确！');
            }
        })

        //上传成功
        uploader.on('uploadSuccess',function(file,response){
            var $li = $( '#headimgPickerTips' );
            if(response.code == 1){
                $('input[name=headimgurl]').val(response.data.path);
            }else{
                $li.html(response.msg);
            }
        })

	})
	
</script>
<script src="/admin/js/plugins/switchery/switchery.js"></script>
<script src="/admin/js/plugins/webuploader/webuploader.min.js"></script>
@endsection

resources/views/admin/manager/manager_edit.blade.php
@extends('admin.layouts.app')
@section('css')
<link href="/admin/css/plugins/switchery/switchery.css" rel="stylesheet">
<link href="/admin/css/plugins/webuploader/webuploader.css" rel="stylesheet">
@endsection
@section('main')
<form method="get" class="form-horizontal" data-event="onform" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">
            <input type="text" value="{{ $info->username }}"  class="form-control" disabled="disabled">
            <span class="help-block m-b-none">登陆账号，介乎4-16个字符</span>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">用户姓名</label>
        <div class="col-sm-10">
            <input type="text" value="{{ $info->name }}" name="name" datatype="s2-16" nullmsg="用户姓名不能为空！" errormsg="用户姓名介乎2-16个字符！" class="form-control" data-trigger="hover">
            <span class="help-block m-b-none">介乎2-16个字符</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">登陆密码</label>
        <div class="col-sm-10">
            <input type="text" name="password" datatype="s8-16" nullmsg="登陆密码不能为空！" errormsg="登陆密码介乎8-16个字符！" class="form-control" data-trigger="hover" ignore="ignore">
            <span class="help-block m-b-none">密码不更改留空</span>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">头像</label>

        <div class="col-sm-6">
   			<input type="text" value="{{ $info->headimgurl }}" datatype="*" nullmsg="头像不能为空！" name="headimgurl" class="form-control" />
        </div>

        <div class="col-sm-4">
            <a type="button" id="headimgPicker">
                <i class="fa fa-upload"></i> 上传头像
            </a>
            <span class="help-block m-b-none" id="headimgPickerTips">
                
            </span>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <label class="col-sm-2 control-label">是否启用</label>

        <div class="col-sm-10">
            <input type="checkbox" name="status" class="js-switch-2" @if($info->status == 1) checked @endif/>
        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group">
        <div class="col-sm-4 col-sm-offset-2">
            <button class="btn btn-primary" type="submit">保存</button>
        </div>
    </div>
</form>

@endsection
@section('script')
<script type="text/javascript">
	//swich按钮
	$(function($){

		var elem2 = document.querySelector('.js-switch-2');
		var init2 = new Switchery(elem2);

        var uploader = WebUploader.create({
            //是否自动上传
            auto : true,
            // swf文件路径
            swf: CT.JS + '/plugins/webuploader/uploader.swf',

            // 文件接收服务端。
            server: '{{ URL::route("admin.attachment.upload.save") }}',

            // 选择文件的按钮。可选。
            // 内部根据当前运行是创建，可能是input元素，也可能是flash.
            pick: {
                id: '#headimgPicker',
                multiple: false
            },

            // 不压缩image, 默认如果是jpeg，文件上传前会压缩一把再上传！
            // resize: false
            accept: {
                title: 'Images',
                extensions: 'gif,jpg,jpeg,bmp,png',
                mimeTypes: 'image/*'
            },
            fileVal: 'file',
            fileSingleSizeLimit: 200*1024,
            //可重复上传
            duplicate :true
        });

        uploader.on('uploadBeforeSend',function (object ,data ,headers){
            headers['X-CSRF-TOKEN']=  $('meta[name="csrf-token"]').attr('content');
        });

        // 文件上传过程中创建进度条实时显示。
        uploader.on( 'uploadProgress', function( file, percentage ) {
            var $li = $( '#headimgPickerTips' ),
                $percent = $li.find('#headimgprocess');

            // 避免重复创建
            if ( !$percent.length ) {
                $percent = $('<div id="headimgprocess"><h5>0%</h5><div class="progress progress-mini"><div style="width: 0%;" class="progress-bar"></div></div>');
                $li.html($percent);
            }

            $percent.find('h5').html(percentage * 100 + '%').end().find('.progress-bar').css( 'width', percentage * 100 + '%' );
        });


        // 文件上传失败，显示上传出错。
        uploader.on( 'uploadError', function( file ) {
            $( '#headimgPickerTips' ).html('上传失败，请重新上传！');
        });

        //选择时出现错误
        uploader.on('error',function(type){
            if(type == 'F_EXCEED_SIZE'){
                tips('文件不能超过200K！');
            }else if (type == 'Q_TYPE_DENIED') {
                tips('文件类型不正确！');
            }
        })

        //上传成功
        uploader.on('uploadSuccess',function(file,response){
            var $li = $( '#headimgPickerTips' );
            if(response.code == 1){
                $('input[name=headimgurl]').val(response.data.path);
            }else{
                $li.html(response.msg);
            }
        })

	})
	
</script>
<script src="/admin/js/plugins/switchery/switchery.js"></script>
<script src="/admin/js/plugins/webuploader/webuploader.min.js"></script>
@endsection

resources/views/admin/manager/manager_list.blade.php
@extends('admin.layouts.app')
@section('main')
<div class="table-responsive">
    <table class="table table-bordered table-striped">
    	<thead>
            <tr>
                <th>#</th>
                <th>用户名</th>
                <th>用户昵称</th>
                <th>用户头像</th>
                <th>状态</th>
                <th>添加时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach($lists as $list)
            <tr>
                <td>{{ $list->admin_id }}</td>
                <td>{{ $list->username }}</td>
                <td>{{ $list->name }}</td>
                <td><img src="{{ $list->headimgurl }}" /></td>
                <td>
                    @if($list->status == 1)
                    <a href="{{ URL::route('admin.manager.changeStatus',['option'=>'status','id'=>$list->admin_id]) }}" data-event="onstatus"><i class="fa fa-check"></i></a>
                    @else
                    <a href="{{ URL::route('admin.manager.changeStatus',['option'=>'status','id'=>$list->admin_id]) }}" data-event="onstatus"><i class="fa fa-close"></i></a>
                    @endif
                </td>
                <td>{{ $list->create_at }}</td>
                <td>
                    <a href="{{ URL::route('admin.manager.edit',['id'=>$list->admin_id]) }}" class="btn btn-white btn-bitbucket btn-sm"><i class="fa fa-paste"></i> 编辑</a>
                    <a href="{{ URL::route('admin.manager.role',['id'=>$list->admin_id]) }}" class="btn btn-white btn-bitbucket btn-sm" data-title="{{$list->username}}-分配角色"><i class="fa fa-group"></i> 分配角色</a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-sm-12">
        {{$lists->links()}}
    </div>
</div>
@endsection

resources/views/admin/manager/manager_role.blade.php
@extends('admin.layouts.app_none')
@section('main')
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>角色分配</h5>
        <div class="ibox-tools">
            <a class="refresh-link" title="刷新" data-event="onrefresh">
                <i class="fa fa-refresh"></i>
            </a>
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
    <div class="ibox-content">
        <h1 class="title">{{$info->username}}</h1>
        <p>可以为管理员分配多个角色</p>
    </div>
</div>
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>角色列表</h5>
        <div class="ibox-tools">
            <a class="refresh-link" title="刷新" data-event="onrefresh">
                <i class="fa fa-refresh"></i>
            </a>
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
    <div class="ibox-content">
        <form data-event="onform">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>角色名</th>
                        <th>描述</th>
                        <th>加入</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($role_list as $list)
                    <tr>
                        <td>{{$list->role_id}}</td>
                        <td>{{$list->name}}</td>
                        <td>{{$list->remark}}</td>
                        <td class="text-navy">  <input ignore="ignore" value="{{$list->role_id}}" type="checkbox" class="i-checks" name="role_id[]" @if(in_array($list->role_id,$role_ids)) checked="" @endif> </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            <div class="hr-line-dashed"></div>
            <button class="btn btn-primary" type="submit">保存</button>     
        </form>  
    </div>
</div>
@endsection